include:
  - project: algebananazzzzz/gitlabtemplates
    ref: main
    file:
      - Vars/aws-vars.yml
      - Jobs/terraform-jobs.yml
      - Jobs/golang-jobs.yml

variables:
  ENV:
    value: "dev"
    options:
      - "dev"
      - "prd"
    description: "The target environment for deployment"
  WORKSPACE:
    value: $ENV-webappdb
  TF_DIR: $CI_PROJECT_DIR/infra
  extends: .aws-vars:all

stages:
  - "build"
  - "test"
  - "deploy"

go-build:
  stage: build
  variables:
    SOURCE_DIR: $CI_PROJECT_DIR/src
    OUTPUT_PATH: $CI_PROJECT_DIR/build/bootstrap
  extends: 
    - .golang:build
  
terraform-plan:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    TF_VAR_FILE: config/$ENV.tfvars
  extends:
    - .terraform:plan
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

terraform-apply:
  stage: deploy
  dependencies:
    - terraform-plan
  extends:
    - .terraform:apply
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"