env = "prd"
project_name = "SimpleApi"
deployment_package_location = "../build"
custom_domain_name = "simpleapi.algebananazzzzz.com"
regional_certificate_domain = "*.algebananazzzzz.com"
route53_zone_name = "algebananazzzzz.com"